# Forced scheduler with temperature stop condition
# - The scheduler runs normally during the configured time range
# - If the water temperature reaches the configured limit while the scheduler is active,
#   the forced scheduler switch is turned OFF immediately
# - No other behavior is modified: no restart logic, no day/night logic added
# - If the temperature is not reached, the scheduler runs until the normal end time
substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

script:
  # A fake empty script to run if user don't provide a custom one
  - id: ${scheduler_unique_id}_fake_script
    then:

switch:
  # Define if scheduler is active or not
  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    id: "${scheduler_unique_id}_scheduler_activate"
    on_turn_off:
      then:
        - if:
            condition:
              - switch.is_off: activate
            then:
              # Stop heating cleanly
              - number.set:
                  id: router_level
                  value: 0
              - switch.turn_on: activate

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: "${scheduler_unique_id}_scheduler_router_level"
    min_value: 0
    max_value: 100
    initial_value: 100
    step: 1
    unit_of_measurement: "%"
    optimistic: true
    mode: slider

  - platform: template
    name: "${scheduler_unique_id} Scheduler Checking End Threshold"
    id: "${scheduler_unique_id}_scheduler_checking_end_threshold"
    optimistic: true
    min_value: 0
    max_value: 720
    step: 5
    mode: box
    initial_value: 5

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Minute"
    id: "${scheduler_unique_id}_scheduler_begin_min"
    optimistic: true
    min_value: 0
    max_value: 55
    step: 5
    mode: box
    initial_value: 0

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Minute"
    id: "${scheduler_unique_id}_scheduler_end_min"
    optimistic: true
    min_value: 0
    max_value: 55
    step: 5
    mode: box
    initial_value: 0

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour"
    id: "${scheduler_unique_id}_scheduler_begin_hour"
    optimistic: true
    min_value: 0
    max_value: 23
    step: 1
    mode: box
    initial_value: 22

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour"
    id: "${scheduler_unique_id}_scheduler_end_hour"
    optimistic: true
    min_value: 0
    max_value: 23
    step: 1
    mode: box
    initial_value: 6

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      - seconds: 0
        minutes: /5
        then:
          - if:
              condition:
                - switch.is_on: ${scheduler_unique_id}_scheduler_activate
              then:
                - if:
                    condition:
                      lambda: |-
                        int beginTotalMinutes = id(${scheduler_unique_id}_scheduler_begin_hour).state * 60
                          + id(${scheduler_unique_id}_scheduler_begin_min).state;
                        int endTotalMinutes = id(${scheduler_unique_id}_scheduler_end_hour).state * 60
                          + id(${scheduler_unique_id}_scheduler_end_min).state;
                        int nowMinutes = id(${scheduler_unique_id}_sntp).now().hour * 60
                          + id(${scheduler_unique_id}_sntp).now().minute;

                        bool in_range;
                        if (beginTotalMinutes <= endTotalMinutes) {
                          in_range = nowMinutes >= beginTotalMinutes && nowMinutes < endTotalMinutes;
                        } else {
                          in_range = nowMinutes >= beginTotalMinutes || nowMinutes < endTotalMinutes;
                        }

                        return in_range;
                    then:
                      # 🔥 SAFETY TEMPERATURE CHECK 🔥
                      - if:
                          condition:
                            lambda: |-
                              return id(safety_limit);
                          then:
                            - logger.log:
                                level: WARN
                                format: "Forced scheduler stopped: temperature limit reached (%.1f°C)"
                                args: [ 'id(safety_temperature).state' ]
                            - switch.turn_off: ${scheduler_unique_id}_scheduler_activate
                          else:
                            # Normal scheduler behavior
                            - switch.turn_off: activate
                            - number.set:
                                id: router_level
                                value: !lambda return id(${scheduler_unique_id}_scheduler_router_level).state;
                            - script.execute: ${custom_script}
                    else:
                      - if:
                          condition:
                            and:
                              - switch.is_off: activate
                              - lambda: |-
                                  int endMinutes = id(${scheduler_unique_id}_scheduler_end_hour).state * 60
                                    + id(${scheduler_unique_id}_scheduler_end_min).state;
                                  int nowMinutes = id(${scheduler_unique_id}_sntp).now().hour * 60
                                    + id(${scheduler_unique_id}_sntp).now().minute;
                                  int threshold = id(${scheduler_unique_id}_scheduler_checking_end_threshold).state;
                                  return nowMinutes >= endMinutes && nowMinutes <= (endMinutes + threshold);
                          then:
                            - number.set:
                                id: router_level
                                value: 0
                            - switch.turn_on: activate
