# Differences from original scheduler:
# - Scheduler parameters (hours, minutes, threshold) are now persistent across reboots
# - Scheduler actions are applied immediately on boot if current time is inside the window
# - Safety limit is checked before forcing router activation
# - Uses numeric inputs (box) instead of sliders to prevent ESP crashes
substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

esphome:
  on_boot:
    priority: -100.0
    then:
      - script.execute: ${scheduler_unique_id}_scheduler_evaluate

script:
  # Fake empty script if user does not provide one
  - id: ${scheduler_unique_id}_fake_script
    then:

  # Central scheduler evaluation (used on boot + every 5 minutes)
  - id: ${scheduler_unique_id}_scheduler_evaluate
    mode: restart
    then:
      - if:
          condition:
            - switch.is_on: ${scheduler_unique_id}_scheduler_activate
            - lambda: |-
                int beginTotal = id(${scheduler_unique_id}_scheduler_begin_hour).state * 60
                               + id(${scheduler_unique_id}_scheduler_begin_min).state;
                int endTotal = id(${scheduler_unique_id}_scheduler_end_hour).state * 60
                             + id(${scheduler_unique_id}_scheduler_end_min).state;
                int nowTotal = id(${scheduler_unique_id}_sntp).now().hour * 60
                             + id(${scheduler_unique_id}_sntp).now().minute;

                if (beginTotal <= endTotal) {
                  return nowTotal >= beginTotal && nowTotal < endTotal;
                } else {
                  return nowTotal >= beginTotal || nowTotal < endTotal;
                }
          then:
            # Inside scheduler window
            - if:
                condition:
                  lambda: return !id(safety_limit);
                then:
                  - switch.turn_off: activate
                  - number.set:
                      id: router_level
                      value: !lambda return id(${scheduler_unique_id}_scheduler_router_level).state;
                  - script.execute: ${custom_script}
          else:
            # Outside scheduler window → restore router
            - if:
                condition:
                  - switch.is_off: activate
                then:
                  - number.set:
                      id: router_level
                      value: 0
                  - switch.turn_on: activate

switch:
  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    id: ${scheduler_unique_id}_scheduler_activate
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: ${scheduler_unique_id}_scheduler_router_level
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 100
    restore_value: true
    optimistic: true
    mode: box
    unit_of_measurement: "%"

  - platform: template
    name: "${scheduler_unique_id} Scheduler Checking End Threshold"
    id: ${scheduler_unique_id}_scheduler_checking_end_threshold
    min_value: 0
    max_value: 720
    step: 5
    restore_value: true
    optimistic: true
    mode: box

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Minute"
    id: ${scheduler_unique_id}_scheduler_begin_min
    min_value: 0
    max_value: 59
    step: 1
    restore_value: true
    optimistic: true
    mode: box

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Minute"
    id: ${scheduler_unique_id}_scheduler_end_min
    min_value: 0
    max_value: 59
    step: 1
    restore_value: true
    optimistic: true
    mode: box

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour"
    id: ${scheduler_unique_id}_scheduler_begin_hour
    min_value: 0
    max_value: 23
    step: 1
    restore_value: true
    optimistic: true
    mode: box

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour"
    id: ${scheduler_unique_id}_scheduler_end_hour
    min_value: 0
    max_value: 23
    step: 1
    restore_value: true
    optimistic: true
    mode: box

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      - seconds: 0
        minutes: /5
        then:
          - script.execute: ${scheduler_unique_id}_scheduler_evaluate
