# ============================================================
# Forced Scheduler with Temperature Guard & Daily Memory
#
# - Stops Forced Scheduler if stop_temperature is reached
# - Stops Forced Scheduler if Safety limit is active
# - Remembers if temperature was reached during the day
# - Memory is persistent across reboot
# - Memory resets every day at 08:00
# - Checks every minute
# ============================================================

substitutions:
  scheduler_unique_id: "Forced"
  custom_script: ${scheduler_unique_id}_fake_script

globals:
  - id: temperature_atteinte_60
    type: bool
    restore_value: yes
    initial_value: "false"

script:
  # Dummy script if user doesn't define one
  - id: ${scheduler_unique_id}_fake_script
    then:

  # ==========================================================
  # TEMPERATURE / SAFETY GUARD
  # ==========================================================
  - id: ${scheduler_unique_id}_temperature_guard
    mode: single
    then:
      - lambda: |-
          auto now = id(${scheduler_unique_id}_sntp).now();
          if (!now.is_valid()) return;

          int now_min = now.hour * 60 + now.minute;

          int begin_min =
            id(${scheduler_unique_id}_scheduler_begin_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_begin_min).state;

          int end_min =
            id(${scheduler_unique_id}_scheduler_end_hour).state * 60 +
            id(${scheduler_unique_id}_scheduler_end_min).state;

          bool in_scheduler_window;
          if (begin_min <= end_min) {
            in_scheduler_window = (now_min >= begin_min && now_min < end_min);
          } else {
            in_scheduler_window = (now_min >= begin_min || now_min < end_min);
          }

          bool temp_reached =
            !isnan(id(safety_temperature).state) &&
            id(safety_temperature).state >= id(stop_temperature).state;

          // --------------------------------------------------
          // DAYTIME (08:00 → 19:00) : remember if temp reached
          // --------------------------------------------------
          if (now.hour >= 8 && now.hour < 19) {
            if (temp_reached || id(safety_limit)) {
              id(temperature_atteinte_60) = true;
            }
            return;
          }

          // --------------------------------------------------
          // NIGHT : block forced scheduler if already heated
          // --------------------------------------------------
          if (id(temperature_atteinte_60)) {
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
            return;
          }

          // --------------------------------------------------
          // Inside scheduler window → safety stop
          // --------------------------------------------------
          if (!in_scheduler_window) return;

          if (temp_reached || id(safety_limit)) {
            ESP_LOGW("forced_scheduler",
              "STOP Forced Scheduler (temp=%.1f safety=%d)",
              id(safety_temperature).state,
              id(safety_limit)
            );
            id(${scheduler_unique_id}_scheduler_activate).turn_off();
          }

switch:
  - platform: template
    name: "Activate ${scheduler_unique_id} Scheduler"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    id: "${scheduler_unique_id}_scheduler_activate"
    on_turn_off:
      then:
        - if:
            condition:
              - switch.is_off: activate
            then:
              - number.set:
                  id: router_level
                  value: 0
              - switch.turn_on: activate

  # Exposed helper switch in Home Assistant
  - platform: template
    name: "Temperature atteinte aujourd'hui"
    id: temperature_atteinte_60_switch
    optimistic: true
    lambda: |-
      return id(temperature_atteinte_60);
    turn_on_action:
      - lambda: id(temperature_atteinte_60) = true;
    turn_off_action:
      - lambda: id(temperature_atteinte_60) = false;

number:
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: "${scheduler_unique_id}_scheduler_router_level"
    min_value: 0
    max_value: 100
    initial_value: 100
    step: 1
    unit_of_measurement: "%"
    optimistic: true
    mode: slider

  - platform: template
    name: "${scheduler_unique_id} Scheduler Checking End Threshold"
    id: "${scheduler_unique_id}_scheduler_checking_end_threshold"
    min_value: 0
    max_value: 720
    step: 5
    initial_value: 5
    optimistic: true
    mode: box

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Minute"
    id: "${scheduler_unique_id}_scheduler_begin_min"
    min_value: 0
    max_value: 55
    step: 5
    initial_value: 0
    optimistic: true
    mode: box

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Minute"
    id: "${scheduler_unique_id}_scheduler_end_min"
    min_value: 0
    max_value: 55
    step: 5
    initial_value: 0
    optimistic: true
    mode: box

  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour"
    id: "${scheduler_unique_id}_scheduler_begin_hour"
    min_value: 0
    max_value: 23
    step: 1
    initial_value: 22
    optimistic: true
    mode: box

  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour"
    id: "${scheduler_unique_id}_scheduler_end_hour"
    min_value: 0
    max_value: 23
    step: 1
    initial_value: 6
    optimistic: true
    mode: box

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      # Reset daily memory at 08:00
      - hours: 8
        minutes: 0
        seconds: 0
        then:
          - lambda: |-
              id(temperature_atteinte_60) = false;

      # Temperature guard every minute
      - seconds: 0
        minutes: /1
        then:
          - script.execute: ${scheduler_unique_id}_temperature_guard
